package types

var RoadTypes = []FeatCode{
	FEAT_MOTORWAY,
	FEAT_PRIMARY_ROAD,
	FEAT_A_ROAD,
	FEAT_B_ROAD,
	FEAT_MINOR_ROAD,
	FEAT_LOCAL_STREET,
	FEAT_PRIVATE_ROAD,
	FEAT_PEDESTRIAN_STREET,
	FEAT_MOTORWAY_COLLAPSED_DUAL_CARRIAGEWAY,
	FEAT_PRIMARY_ROAD_COLLAPSED_DUAL_CARRIAGEWAY,
	FEAT_A_ROAD_COLLAPSED_DUAL_CARRIAGEWAY,
	FEAT_B_ROAD_COLLAPSED_DUAL_CARRIAGEWAY,
	FEAT_MINOR_ROAD_COLLAPSED_DUAL_CARRIAGEWAY,
}
