// Code generated by "stringer -type=TextFormat"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HEIGHTPOINT-0]
	_ = x[LABEL-1]
	_ = x[MOTORWAY-2]
	_ = x[PRIMARY_ROAD-3]
	_ = x[A_ROAD-4]
	_ = x[B_ROAD-5]
	_ = x[MINOR_ROAD-6]
	_ = x[LOCAL_STREET-7]
	_ = x[PRIVATE_ROAD-8]
	_ = x[PEDESTRIAN_STREET-9]
	_ = x[ROAD_TUNNEL-10]
	_ = x[MOTORWAY_JN-11]
	_ = x[HYDROGRAPHY-12]
	_ = x[CT_SMALL-13]
	_ = x[CT_MEDIUM-14]
	_ = x[CT_LARGE-15]
	_ = x[CT_EXTRA_LARGE-16]
}

const _TextFormat_name = "HEIGHTPOINTLABELMOTORWAYPRIMARY_ROADA_ROADB_ROADMINOR_ROADLOCAL_STREETPRIVATE_ROADPEDESTRIAN_STREETROAD_TUNNELMOTORWAY_JNHYDROGRAPHYCT_SMALLCT_MEDIUMCT_LARGECT_EXTRA_LARGE"

var _TextFormat_index = [...]uint8{0, 11, 16, 24, 36, 42, 48, 58, 70, 82, 99, 110, 121, 132, 140, 149, 157, 171}

func (i TextFormat) String() string {
	if i < 0 || i >= TextFormat(len(_TextFormat_index)-1) {
		return "TextFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TextFormat_name[_TextFormat_index[i]:_TextFormat_index[i+1]]
}
